<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PatientVisitPriceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('patient_visit_price')->insert([
            [
                'hms_id' => 1,
                'branch_id' => 1,
                'patient_type_id' => 1,
                'department_type_id' => 1,
                'clinical_service_id' => 1,
                'price' => .00,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hms_id' => 1,
                'branch_id' => 1,
                'patient_type_id' => 1,
                'department_type_id' => 1,
                'clinical_service_id' => 2,
                'price' => .00,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hms_id' => 1,
                'branch_id' => 1,
                'patient_type_id' => 1,
                'department_type_id' => 1,
                'clinical_service_id' => 3,
                'price' => .00,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hms_id' => 1,
                'branch_id' => 1,
                'patient_type_id' => 1,
                'department_type_id' => 2,
                'clinical_service_id' => 1,
                'price' => 200,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hms_id' => 1,
                'branch_id' => 1,
                'patient_type_id' => 1,
                'department_type_id' => 2,
                'clinical_service_id' => 2,
                'price' => 250.00,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hms_id' => 1,
                'branch_id' => 1,
                'patient_type_id' => 1,
                'department_type_id' => 2,
                'clinical_service_id' => 3,
                'price' => 200.00,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hms_id' => 1,
                'branch_id' => 1,
                'patient_type_id' => 1,
                'department_type_id' => 3,
                'clinical_service_id' => 1,
                'price' => .00,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hms_id' => 1,
                'branch_id' => 1,
                'patient_type_id' => 1,
                'department_type_id' => 3,
                'clinical_service_id' => 2,
                'price' => .00,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hms_id' => 1,
                'branch_id' => 1,
                'patient_type_id' => 1,
                'department_type_id' => 3,
                'clinical_service_id' => 3,
                'price' => .00,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            //aaaaaaaaaaaa
            [
                'hms_id' => 1,
                'branch_id' => 1,
                'patient_type_id' => 2,
                'department_type_id' => 1,
                'clinical_service_id' => 1,
                'price' => .00,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hms_id' => 1,
                'branch_id' => 1,
                'patient_type_id' => 2,
                'department_type_id' => 1,
                'clinical_service_id' => 2,
                'price' => .00,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hms_id' => 1,
                'branch_id' => 1,
                'patient_type_id' => 2,
                'department_type_id' => 1,
                'clinical_service_id' => 3,
                'price' => .00,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hms_id' => 1,
                'branch_id' => 1,
                'patient_type_id' => 2,
                'department_type_id' => 2,
                'clinical_service_id' => 1,
                'price' => 200,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hms_id' => 1,
                'branch_id' => 1,
                'patient_type_id' => 2,
                'department_type_id' => 2,
                'clinical_service_id' => 2,
                'price' => 250.00,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hms_id' => 1,
                'branch_id' => 1,
                'patient_type_id' => 2,
                'department_type_id' => 2,
                'clinical_service_id' => 3,
                'price' => 200.00,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hms_id' => 1,
                'branch_id' => 1,
                'patient_type_id' => 2,
                'department_type_id' => 3,
                'clinical_service_id' => 1,
                'price' => .00,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hms_id' => 1,
                'branch_id' => 1,
                'patient_type_id' => 2,
                'department_type_id' => 3,
                'clinical_service_id' => 2,
                'price' => .00,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hms_id' => 1,
                'branch_id' => 1,
                'patient_type_id' => 2,
                'department_type_id' => 3,
                'clinical_service_id' => 3,
                'price' => .00,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            //qqqqqqqqqqqqqqqq

            [
                'hms_id' => 1,
                'branch_id' => 1,
                'patient_type_id' => 3,
                'department_type_id' => 1,
                'clinical_service_id' => 1,
                'price' => 200,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hms_id' => 1,
                'branch_id' => 1,
                'patient_type_id' => 3,
                'department_type_id' => 1,
                'clinical_service_id' => 2,
                'price' => 200,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hms_id' => 1,
                'branch_id' => 1,
                'patient_type_id' => 3,
                'department_type_id' => 1,
                'clinical_service_id' => 3,
                'price' => 200,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hms_id' => 1,
                'branch_id' => 1,
                'patient_type_id' => 3,
                'department_type_id' => 2,
                'clinical_service_id' => 1,
                'price' => 200,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hms_id' => 1,
                'branch_id' => 1,
                'patient_type_id' => 3,
                'department_type_id' => 2,
                'clinical_service_id' => 2,
                'price' => 200.00,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hms_id' => 1,
                'branch_id' => 1,
                'patient_type_id' => 3,
                'department_type_id' => 2,
                'clinical_service_id' => 3,
                'price' => 200.00,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hms_id' => 1,
                'branch_id' => 1,
                'patient_type_id' => 3,
                'department_type_id' => 3,
                'clinical_service_id' => 1,
                'price' => 50,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hms_id' => 1,
                'branch_id' => 1,
                'patient_type_id' => 3,
                'department_type_id' => 3,
                'clinical_service_id' => 2,
                'price' => 200,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hms_id' => 1,
                'branch_id' => 1,
                'patient_type_id' => 1,
                'department_type_id' => 3,
                'clinical_service_id' => 3,
                'price' => 50,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
